{
  "Name": "debug_data_multi - MAIN",
  "Description": "debug",
  "CycleEndDate": "2023-08-02T00:00:00",
  "EndDate": "Wednesday, 2 August 2023",
  "Budget": 2000.0,
  "DataCurrency": {
    "Code": "EUR",
    "Name": "Euro",
    "Symbol": "€"
  },
  "Currency": "en-DE",
  "CurrencySymbol": "€",
  "Entries": [
    {
      "Description": "sample",
      "Amount": 100.0,
      "OriginalAmount": 0.0,
      "Category": null,
      "PaymentChannel": "Citibank",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "EUR",
        "Name": "Euro",
        "Symbol": "€"
      }
    },
    {
      "Description": "testing php",
      "Amount": 163.8,
      "OriginalAmount": 10000.0,
      "Category": null,
      "PaymentChannel": "BPI-Car",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      }
    },
    {
      "Description": "tesing other php",
      "Amount": 50.15,
      "OriginalAmount": 3000.0,
      "Category": null,
      "PaymentChannel": "Citibank",
      "ExpenseCategory": "Subscriptions",
      "Comments": "test2",
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      }
    }
  ],
  "Report": {
    "ExpenseCategoryReportCounter": {
      "Food": 5,
      "Subscriptions": 1
    },
    "TotalAmount": 460.74,
    "Savings": 1539.26,
    "UnPaidAmount": 460.74,
    "PaidAmount": 0.0,
    "Completed": false,
    "CategoryReports": [
      {
        "PaymentChannel": "Citibank",
        "Amount": 168.69,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 168.69
      },
      {
        "PaymentChannel": "BPI-Car",
        "Amount": 163.8,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 163.8
      },
      {
        "PaymentChannel": "BPI Credit",
        "Amount": 81.9,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 81.9
      },
      {
        "PaymentChannel": "RobinsonsBank",
        "Amount": 46.35,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 46.35
      }
    ],
    "SelectedReport": null,
    "DataCurrency": {
      "Code": "EUR",
      "Name": "Euro",
      "Symbol": "€"
    },
    "CurrencySymbol": "€",
    "ReportChartData": [
      {
        "Key": "Citibank",
        "Value": 169
      },
      {
        "Key": "BPI-Car",
        "Value": 164
      },
      {
        "Key": "BPI Credit",
        "Value": 82
      },
      {
        "Key": "RobinsonsBank",
        "Value": 46
      }
    ],
    "ExpenseCategoryChartData": [
      {
        "Key": "Food",
        "Value": 5
      },
      {
        "Key": "Subscriptions",
        "Value": 1
      }
    ],
    "CurrencyReport": [
      {
        "Currency": {
          "Code": "PHP",
          "Name": "Philippine Piso",
          "Symbol": "₱"
        },
        "Amount": 18000.0
      },
      {
        "Currency": {
          "Code": "USD",
          "Name": "US Dollar",
          "Symbol": "$"
        },
        "Amount": 70.0
      }
    ],
    "AltCurrencyBreakdown": [
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "BPI-Car",
        "Amount": 10000.0
      },
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "Citibank",
        "Amount": 3020.0
      },
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "BPI Credit",
        "Amount": 5000.0
      },
      {
        "CurrencyCode": "USD",
        "PaymentChannel": "RobinsonsBank",
        "Amount": 50.0
      }
    ]
  }
}