{
  "Name": "!debug - ALT",
  "Description": "debug",
  "CycleEndDate": "2023-08-02T00:00:00",
  "EndDate": "Wednesday, 2 August 2023",
  "Budget": 2000.0,
  "DataCurrency": {
    "Code": "EUR",
    "Name": "Euro",
    "Symbol": "€"
  },
  "Currency": "en-DE",
  "CurrencySymbol": "€",
  "Entries": [
    {
      "Description": "sample",
      "Amount": 100.0,
      "OriginalAmount": 0.0,
      "Category": null,
      "PaymentChannel": "Credit Card",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "EUR",
        "Name": "Euro",
        "Symbol": "€"
      }
    },
    {
      "Description": "testing php",
      "Amount": 163.8,
      "OriginalAmount": 10000.0,
      "Category": null,
      "PaymentChannel": "Credit Card",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      }
    }
  ],
  "Report": {
    "ExpenseCategoryReportCounter": {
      "Food": 2
    },
    "TotalAmount": 263.8,
    "Savings": 1736.2,
    "UnPaidAmount": 263.8,
    "PaidAmount": 0.0,
    "Completed": false,
    "CategoryReports": [
      {
        "PaymentChannel": "Credit Card",
        "Amount": 263.8,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 263.8,
        "CategoryBreakdown": [
          {
            "Category": "Food",
            "TotalAmount": 0.0
          }
        ]
      }
    ],
    "SelectedReport": null,
    "DataCurrency": {
      "Code": "EUR",
      "Name": "Euro",
      "Symbol": "€"
    },
    "CurrencySymbol": "€",
    "ReportChartData": [
      {
        "Key": "Credit Card",
        "Value": 264
      }
    ],
    "ExpenseCategoryChartData": [
      {
        "Key": "Food",
        "Value": 2
      }
    ],
    "ExpenseCategoryExpenseTotalValueData": [
      {
        "Key": "Food",
        "Value": 0.0
      }
    ],
    "CurrencyReport": [
      {
        "Currency": {
          "Code": "PHP",
          "Name": "Philippine Piso",
          "Symbol": "₱"
        },
        "Amount": 10000.0
      }
    ],
    "AltCurrencyBreakdown": [
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "Credit Card",
        "Amount": 10000.0
      }
    ]
  },
  "UniqueGuid": "7a37c304-9460-4b6c-a42e-32a8e929653d"
}