{
  "Name": "debug_data_multi",
  "Description": "debug",
  "CycleEndDate": "2023-08-02T00:00:00",
  "EndDate": "Wednesday, 2 August 2023",
  "Budget": 2000.0,
  "DataCurrency": {
    "Code": "EUR",
    "Name": "Euro",
    "Symbol": "€"
  },
  "Currency": "en-DE",
  "CurrencySymbol": "€",
  "Entries": [
    {
      "Description": "sample",
      "Amount": 100.0,
      "OriginalAmount": 0.0,
      "Category": null,
      "PaymentChannel": "RobinsonsBank",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "EUR",
        "Name": "Euro",
        "Symbol": "€"
      },
      "EntryDate": null,
      "LastUpdated": "04/08/2024 14:26:27",
      "GetMetaData": "Created: \nUpdated: 04/08/2024 14:26:27"
    },
    {
      "Description": "Test Investment",
      "Amount": 163.8,
      "OriginalAmount": 10000.0,
      "Category": null,
      "PaymentChannel": "Investment",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      },
      "EntryDate": null,
      "LastUpdated": "04/08/2024 14:26:33",
      "GetMetaData": "Created: \nUpdated: 04/08/2024 14:26:33"
    },
    {
      "Description": "tesing other php",
      "Amount": 50.15,
      "OriginalAmount": 3000.0,
      "Category": null,
      "PaymentChannel": "Cash",
      "ExpenseCategory": "Subscriptions",
      "Comments": "test2",
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      },
      "EntryDate": null,
      "LastUpdated": "04/08/2024 14:26:22",
      "GetMetaData": "Created: \nUpdated: 04/08/2024 14:26:22"
    },
    {
      "Description": "testing USD",
      "Amount": 109.88,
      "OriginalAmount": 120.0,
      "Category": null,
      "PaymentChannel": "SSS",
      "ExpenseCategory": "Bills",
      "Comments": null,
      "Currency": {
        "Code": "USD",
        "Name": "US Dollar",
        "Symbol": "$"
      },
      "EntryDate": "04/08/2024 14:26:56",
      "LastUpdated": "04/08/2024 14:26:56",
      "GetMetaData": "Created: 04/08/2024 14:26:56\nUpdated: 04/08/2024 14:26:56"
    }
  ],
  "Report": {
    "ExpenseCategoryReportCounter": {
      "Food": 2,
      "Subscriptions": 1,
      "Bills": 1
    },
    "TotalAmount": 423.83,
    "Savings": 1576.17,
    "UnPaidAmount": 423.83,
    "PaidAmount": 0.0,
    "Completed": false,
    "CategoryReports": [
      {
        "PaymentChannel": "RobinsonsBank",
        "Amount": 100.0,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 100.0
      },
      {
        "PaymentChannel": "Investment",
        "Amount": 163.8,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 163.8
      },
      {
        "PaymentChannel": "Cash",
        "Amount": 50.15,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 50.15
      },
      {
        "PaymentChannel": "SSS",
        "Amount": 109.88,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 109.88
      }
    ],
    "SelectedReport": null,
    "DataCurrency": {
      "Code": "EUR",
      "Name": "Euro",
      "Symbol": "€"
    },
    "CurrencySymbol": "€",
    "ReportChartData": [
      {
        "Key": "RobinsonsBank",
        "Value": 100
      },
      {
        "Key": "Investment",
        "Value": 164
      },
      {
        "Key": "Cash",
        "Value": 50
      },
      {
        "Key": "SSS",
        "Value": 110
      }
    ],
    "ExpenseCategoryChartData": [
      {
        "Key": "Food",
        "Value": 2
      },
      {
        "Key": "Subscriptions",
        "Value": 1
      },
      {
        "Key": "Bills",
        "Value": 1
      }
    ],
    "CurrencyReport": [
      {
        "Currency": {
          "Code": "PHP",
          "Name": "Philippine Piso",
          "Symbol": "₱"
        },
        "Amount": 13000.0
      },
      {
        "Currency": {
          "Code": "USD",
          "Name": "US Dollar",
          "Symbol": "$"
        },
        "Amount": 120.0
      }
    ],
    "AltCurrencyBreakdown": [
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "Investment",
        "Amount": 10000.0
      },
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "Cash",
        "Amount": 3000.0
      },
      {
        "CurrencyCode": "USD",
        "PaymentChannel": "SSS",
        "Amount": 120.0
      }
    ]
  }
}