{
  "Name": "!debug - ALT",
  "Description": "debug",
  "CycleEndDate": "2023-08-02T00:00:00",
  "EndDate": "Wednesday, 2 August 2023",
  "Budget": 2000.0,
  "DataCurrency": {
    "Code": "EUR",
    "Name": "Euro",
    "Symbol": "€"
  },
  "Currency": "en-DE",
  "CurrencySymbol": "€",
  "Entries": [
    {
      "Description": "sample",
      "Amount": 100.0,
      "OriginalAmount": 0.0,
      "Category": null,
      "PaymentChannel": "Credit Card",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "EUR",
        "Name": "Euro",
        "Symbol": "€"
      }
    },
    {
      "Description": "testing php",
      "Amount": 163.8,
      "OriginalAmount": 10000.0,
      "Category": null,
      "PaymentChannel": "Credit Card",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      }
    },
    {
      "Description": "tesing other php",
      "Amount": 50.15,
      "OriginalAmount": 3000.0,
      "Category": null,
      "PaymentChannel": "Loan",
      "ExpenseCategory": "Shopping",
      "Comments": "test2",
      "Currency": {
        "Code": "PHP",
        "Name": "Philippine Piso",
        "Symbol": "₱"
      }
    },
    {
      "Description": "Credit Card Due",
      "Amount": 500.0,
      "OriginalAmount": 0.0,
      "Category": null,
      "PaymentChannel": "Credit Card",
      "ExpenseCategory": "Bills",
      "Comments": null,
      "Currency": {
        "Code": "EUR",
        "Name": "Euro",
        "Symbol": "€"
      }
    },
    {
      "Description": "testing expense - food",
      "Amount": 40.0,
      "OriginalAmount": 0.0,
      "Category": null,
      "PaymentChannel": "Credit Card",
      "ExpenseCategory": "Food",
      "Comments": null,
      "Currency": {
        "Code": "EUR",
        "Name": "Euro",
        "Symbol": "€"
      }
    }
  ],
  "Report": {
    "ExpenseCategoryReportCounter": {
      "Food": 3,
      "Shopping": 1,
      "Bills": 1
    },
    "TotalAmount": 853.95,
    "Savings": 1146.05,
    "UnPaidAmount": 853.95,
    "PaidAmount": 0.0,
    "Completed": false,
    "CategoryReports": [
      {
        "PaymentChannel": "Credit Card",
        "Amount": 803.8,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 803.8,
        "CategoryBreakdown": [
          {
            "Category": "Food",
            "TotalAmount": 0.0
          },
          {
            "Category": "Bills",
            "TotalAmount": 0.0
          }
        ]
      },
      {
        "PaymentChannel": "Loan",
        "Amount": 50.15,
        "Comments": null,
        "Paid": false,
        "PartialPayment": 0.0,
        "OutstandingBalance": 50.15,
        "CategoryBreakdown": [
          {
            "Category": "Shopping",
            "TotalAmount": 0.0
          }
        ]
      }
    ],
    "SelectedReport": null,
    "DataCurrency": {
      "Code": "EUR",
      "Name": "Euro",
      "Symbol": "€"
    },
    "CurrencySymbol": "€",
    "ReportChartData": [
      {
        "Key": "Credit Card",
        "Value": 804
      },
      {
        "Key": "Loan",
        "Value": 50
      }
    ],
    "ExpenseCategoryChartData": [
      {
        "Key": "Food",
        "Value": 3
      },
      {
        "Key": "Shopping",
        "Value": 1
      },
      {
        "Key": "Bills",
        "Value": 1
      }
    ],
    "ExpenseCategoryExpenseTotalValueData": [
      {
        "Key": "Food",
        "Value": 303.8
      },
      {
        "Key": "Bills",
        "Value": 500.0
      },
      {
        "Key": "Shopping",
        "Value": 50.15
      }
    ],
    "CurrencyReport": [
      {
        "Currency": {
          "Code": "PHP",
          "Name": "Philippine Piso",
          "Symbol": "₱"
        },
        "Amount": 13000.0
      }
    ],
    "AltCurrencyBreakdown": [
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "Credit Card",
        "Amount": 10000.0
      },
      {
        "CurrencyCode": "PHP",
        "PaymentChannel": "Loan",
        "Amount": 3000.0
      }
    ]
  },
  "UniqueGuid": "7a37c304-9460-4b6c-a42e-32a8e929653d"
}